version: '3'
services:
  express: 
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
      - CONFIG_JSON_PATH=./BoxJWTConfig.json
      - NGINX=true
  nginx:
    restart: always
    build:
        dockerfile: Dockerfile.dev
        context: ./nginx
    ports:
        - '80:80'
        - '443:443'